#!/bin/sh

# phpMyAdmin configuraiton storage
drizzle -uroot < create_tables_drizzle.sql

# World database
drizzle -uroot <<EOT
DROP SCHEMA IF EXISTS world;
CREATE DATABASE world;
USE world;
\. world-drizzle.sql
EOT
