#!/bin/sh

# Fail on error or undefined variable
set -e
set -u

if ! [ -x "$(command -v wlc)" ]; then
    echo "Please install the Weblate client. Debian/Ubuntu package: wlc"
    echo "Or using PIP: https://github.com/WeblateOrg/wlc#pip-installation"
    exit 1
fi

if [ ! -f ~/.config/weblate ]; then
    echo "Please add a Weblate client API key to a file located at ~/.config/weblate"
    echo "See: https://github.com/WeblateOrg/wlc#usage"
    exit 1
fi

# Updates phpMyAdmin documentation

if [ -z "${1:-}" ] || [ ! -d "${1:-}" ]; then
    echo "Usage documentation-po-update ~/localized_docs/"
    exit 1
fi

WORKDIR="${1}"

if [ ! -d "$WORKDIR" ] ; then
    git clone git@github.com:phpmyadmin/localized_docs.git "$WORKDIR"
fi

cd "$WORKDIR"

# Remove any possible changes
git reset --hard -q

# Update localized_docs repo
git pull -q
git submodule update --init -q

cd phpmyadmin

# Check for remote changes in phpmyadmin repo
oldrev=`git log -n 1 --format=format:%H @`
git fetch -q origin
newrev=`git log -n 1 --format=format:%H origin/master`

# Is there some diff?
if git diff --stat --exit-code $oldrev..$newrev -- docs/ ; then
    exit 0
fi

cd ..

# Lock Weblate and commit changes
wlc lock
wlc push

# Pull changes from weblate
git pull

# Update phpmyadmin submodule
git submodule update --remote
git commit -a -m 'Updated phpMyAdmin repository'

# Update po files
make
git add .
git commit -m 'Update po files'

# Publish changes
git push

# Unlock Weblate
wlc unlock
