#!/bin/sh
set -e

error_handler() {
    if [ -f crash.log ] ; then
        cat crash.log
    fi
}
trap error_handler INT QUIT EXIT

cd /home/pmaweb/pma/website/
svn -q up
./render.py \
    --quiet \
    --server http://www.phpmyadmin.net \
    --base-url /home_page/ \
    --quiet-cache \
    --log render.log \
    --extension php > crash.log 2>&1
cp render.log crash.log output/
rsync -az --delete output/ web.sourceforge.net:htdocs/home_page/
