#!/bin/sh

# Script to publish documentation on phpmyadmin.net

# Main documentation + required files
cd /home/pmaweb/pma/phpMyAdmin/
svn -q up
rsync -az favicon.ico CREDITS ChangeLog Documentation.html INSTALL LICENSE README changelog.php docs.css license.php translators.html web.sourceforge.net:htdocs/documentation/
cd themes/original/img/
rsync -az docs_menu_bg.png logo_right.png web.sourceforge.net:htdocs/documentation/themes/original/img/
cd /home/pmaweb/pma/phpMyAdmin/libraries/
rsync -az vendor_config.php web.sourceforge.net:htdocs/documentation/libraries/

# Localised documentation
cd /home/pmaweb/pma/localized_docs/
svn -q up
cd ..
rsync -az --delete localized_docs/output/ web.sourceforge.net:htdocs/localized_docs/
