#!/bin/sh
export BORG_PASSPHRASE=`cat /etc/borg-key`

# Create new backup
borg create ssh://borgbackup/./backups/`hostname`::'{now:%Y-%m-%d_%H:%M}' `cat /etc/borg-dirs`

# Prune old backups, we keep last year of backups in descending frequency
# - daily backups for 14 days
# - weekly backups for 8 weeks
# - monthly backups for 12 months
borg prune --keep-weekly 8 --keep-monthly 12 --keep-daily 14 ssh://borgbackup/./backups/`hostname`

# Compact repository to free up disk space that is still in use after being de-allocated by prune.
# This is needed since Borg 1.2.0
# Since it doesn't exist prior to 1.2.0, we test so as to avoid failing
if borg help compact  >/dev/null 2>&1; then
  borg compact ssh://borgbackup/./backups/`hostname`
fi
