#!/bin/sh
# Script to generate daily snapshots
set -eux

if [ -z "${1:-}" ] || [ ! -d "${1:-}" ]; then
    echo "Usage daily-snapshots ~/phpmyadmin.git"
    exit 1
fi

# phpMyAdmin working copy
cd "${1}"

# Delete any local changes
git reset --hard

# Update to have latest create-release.sh
git pull -q

# Remove current release files
rm -rf release

# Create snapshots
# Change branch to be sure to have a working release script
git checkout QA_5_2
# Destroy any possible local changes
git reset --hard
# Force an update
git pull --ff-only
#TODO: When changing to QA_6_0, update from ./scripts/ to ./bin/internal/
./scripts/create-release.sh --daily 5.2+snapshot QA_5_2
# Destroy any possible local changes
git reset --hard
git checkout -
git checkout master
# Destroy any possible local changes
git reset --hard
# Force an update
git pull --ff-only
./bin/internal/create-release.sh --daily 6.0+snapshot master

# Storage directory
mkdir -p /mnt/storage/files/snapshots/

# Remove old snapshots
rm -f /mnt/storage/files/snapshots/*

# Move new files
mv release/*.* /mnt/storage/files/snapshots/

# trigger website scan
sudo -u builder /home/builder/website/manage.py import_files
