#!/bin/sh
# Script to generate daily snapshots
set -ex

# phpMyAdmin working copy
cd ~/phpmyadmin

# Delete any local changes
git reset --hard

# Update to have latest create-release.sh
git pull -q

# Remove current release files
rm -rf release

# Create snapshots
# Change branch to be sure to have a working release script
git checkout QA_5_2
# Destroy any possible local changes
git reset --hard
# Force an update
git pull --ff-only
./scripts/create-release.sh --daily 5.2+snapshot QA_5_2
# Destroy any possible local changes
git reset --hard
git checkout -
git checkout master
# Destroy any possible local changes
git reset --hard
# Force an update
git pull --ff-only
./scripts/create-release.sh --daily 5.3+snapshot master

# Storage directory
mkdir -p /mnt/storage/files/snapshots/

# Remove old snapshots
rm -f /mnt/storage/files/snapshots/*

# Move new files
mv release/*.* /mnt/storage/files/snapshots/

# Rsync to CDN
rsync -va /mnt/storage/files/ cdn:/www/

# trigger website scan
cd /home/builder/website/
./manage.py import_files
