#!/bin/sh
# Script to generate daily snapshots
set -e

# phpMyAdmin working copy
cd ~/phpmyadmin

# Update
git pull -q

# Remove current release files
rm -rf release

# Create snapshots
./scripts/create-release.sh --daily 4.7+snapshot QA_4_7
./scripts/create-release.sh --daily 4.8+snapshot master

# Storage directory
mkdir -p /mnt/storage/files/snapshots/

# Remove old snapshots
rm -f /mnt/storage/files/snapshots/*

# Move new files
mv release/*.* /mnt/storage/files/snapshots/

# Rsync to CDN
rsync -va /mnt/storage/files/ cdn:/www/

# trigger website scan
cd /home/builder/website/
./manage.py import_files

# Trigger docker build for edge-4.7
./manage.py docker_trigger --tag edge-4.7
# Triggers are throttled, avoid problem by sleeping
sleep 600
# Trigger docker build for edge-4.8
./manage.py docker_trigger --tag edge-4.8
