#!/bin/sh
set -e

error_handler() {
    if [ -f crash.log ] ; then
        cat crash.log
        cat crash.log >> render.log
        scp render.log web.sourceforge.net:htdocs/home_page/
    fi
}
trap error_handler INT QUIT EXIT

cd /home/builder/website/
git pull -q
./render.py \
    --quiet \
    --server http://www.phpmyadmin.net \
    --base-url /home_page/ \
    --quiet-cache \
    --log render.log \
    --extension php > crash.log 2>&1
date > output/render.log
cat render.log crash.log >> output/render.log
rsync -az --delete output/ web.sourceforge.net:htdocs/home_page/
rm crash.log
