#!/bin/sh

# Script to generate phpdoc documentation of phpMyAdmin and publish it 
# on develdocs.phpmyadmin.net

cd /home/builder/phpmyadmin/
git pull -q
nice -19 phpdox > build/phpdox/html/build.log
