#!/bin/sh

# Script to generate phpdoc documentation of phpMyAdmin and publish it 
# on develdocs.phpmyadmin.net

cd /home/builder/phpmyadmin/
git pull -q
nice -19 phploc --log-xml build/phploc.xml libraries/ > build/phploc.log
nice -19 phpdox > build/phpdox.log
cp build/*.log build/phpdox/html/
