#!/bin/sh

# Script to publish documentation on phpmyadmin.net

# Main documentation + required files
cd /home/pmaweb/pma/phpmyadmin/
git pull -q
rsync -az favicon.ico ChangeLog LICENSE README web.sourceforge.net:htdocs/documentation/
cd /home/pmaweb/pma/phpmyadmin/libraries/
rsync -az vendor_config.php web.sourceforge.net:htdocs/documentation/libraries/
